name: Get YouTube Live m3u8
on:
  schedule:
    - cron: '0 0/3 * * *'

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp
         # 01海豚綜合台
    - name: Get 01.m3u8
      run: |
        touch ./01.m3u8
        sudo cat >./01.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=Z0SWvl1Jt18)
        EOL
        # 02誠心電視台
    - name: Get 02.m3u8
      run: |
        touch ./02.m3u8
        sudo cat >./02.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=IT3ROPSceKc)
        EOL
      # 03信大電視台
    - name: Get 03.m3u8
      run: |
        touch ./03.m3u8
        sudo cat >./03.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=AQymzwl3uSk)
        EOL
      # 04大愛 1臺
    - name: Get 04.m3u8
      run: |
        touch ./04.m3u8
        sudo cat >./04.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=MIqUplvSRWA)
        EOL
       # 05大愛 2臺
    - name: Get 05.m3u8
      run: |
        touch ./05.m3u8
        sudo cat >./05.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=DTNkEm6jaqQ)
        EOL
        # 06萬秀豬王
    - name: Get 06.m3u8
      run: |
        touch ./06.m3u8
        sudo cat >./06.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=ADDSmXoPDY8)
        EOL
       # 07新兵日記(全集)
    - name: Get 07.m3u8
      run: |
        touch ./07.m3u8
        sudo cat >./07.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=bn7glmBPmIQ)
        EOL
        # 08歡喜玉玲瓏(全集)
    - name: Get 08.m3u8
      run: |
        touch ./08.m3u8
        sudo cat >./08.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=r_wsMgFLKys)
        EOL
       # 09風景音樂1
    - name: Get 09.m3u8
      run: |
        touch ./09.m3u8
        sudo cat >./09.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=iSgIBFBIeug&t=1375s)
        EOL
        # 10風景音樂2
    - name: Get 10.m3u8
      run: |
        touch ./10.m3u8
        sudo cat >./10.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=fl0rDnxT3nM)
        EOL
        # 11風景音樂3
    - name: Get 11.m3u8
      run: |
        touch ./11.m3u8
        sudo cat >./11.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=dXIyMS61B68)
        EOL
        # 12風景音樂4
    - name: Get 12.m3u8
      run: |
        touch ./12.m3u8
        sudo cat >./12.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=b-XvnVAdFCM)
        EOL
        # 13風景音樂5
    - name: Get 13.m3u8
      run: |
        touch ./13.m3u8
        sudo cat >./13.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=caN_s19PumQ)
        EOL
        # 14華視新聞資訊
    - name: Get 14.m3u8
      run: |
        touch ./14.m3u8
        sudo cat >./14.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=K2I89l2tDSs)
        EOL
       # 15台視新聞HD
    - name: Get 15.m3u8
      run: |
        touch ./15.m3u8
        sudo cat >./15.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=xL0ch83RAK8)
        EOL
        # 16中視新聞HD
    - name: Get 16.m3u8
      run: |
        touch ./16.m3u8
        sudo cat >./16.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=TCnaIE_SAtM)
        EOL
        # 17公視 HD
    - name: Get 17.m3u8
      run: |
        touch ./17.m3u8
        sudo cat >./17.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=4Uc00FPs27M)
        EOL
        # 18公視台語台 HD
    - name: Get 18.m3u8
      run: |
        touch ./18.m3u8
        sudo cat >./18.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=6KlRR_DGhmI)
        EOL
        # 19桐瑛虎尾電視台
    - name: Get 19.m3u8
      run: |
        touch ./19.m3u8
        sudo cat >./19.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=wnoyoSPZIjs)
        EOL
        # 20中天新聞HD
    - name: Get 20.m3u8
      run: |
        touch ./20.m3u8
        sudo cat >./20.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=Yi6_UCTjCAE)
        EOL
        # 21EBC東森財經新聞HD
    - name: Get 21.m3u8
      run: |
        touch ./21.m3u8
        sudo cat >./21.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=WHEPzbFA3hw)
        EOL
        # 22能登鹿島駅周辺-石川県穴水町
    - name: Get 22.m3u8
      run: |
        touch ./22.m3u8
        sudo cat >./22.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=THy9p2xJSek)
        EOL
        # 23名古屋駅県羽咋市-千里浜
    - name: Get 23.m3u8
      run: |
        touch ./23.m3u8
        sudo cat >./23.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=VcbE3iLfVIw)
        EOL
        # 24浅草寺の境内（本堂側）
    - name: Get 24.m3u8
      run: |
        touch ./24.m3u8
        sudo cat >./24.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=nOk4cd0kkp8)
        EOL
        # 25大阪の夜景-OSAKA NIGHT,
    - name: Get 25.m3u8
      run: |
        touch ./25.m3u8
        sudo cat >./25.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=qz8F44n5DEw)
        EOL
         # 26兼六園ライブカメラ,
    - name: Get 26.m3u8
      run: |
        touch ./26.m3u8
        sudo cat >./26.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=uUTpDBgqQL8)
        EOL
        # 27富士山ライブカメラ-河口湖駅前 
    - name: Get 27.m3u8
      run: |
        touch ./27.m3u8
        sudo cat >./27.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=h6Z9v-qqHl8)
        EOL
       # 28玉泉院丸庭園ライブカメラ
    - name: Get 28.m3u8
      run: |
        touch ./28.m3u8
        sudo cat >./28.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=JpLMmrxB_Tg)
        EOL
        # 29能登珠洲-石川県
    - name: Get 29.m3u8
      run: |
        touch ./29.m3u8
        sudo cat >./29.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=uP2JdvfvqFo)
        EOL
        # 30TAIWAN-8K 60看見台灣
    - name: Get 30.m3u8
      run: |
        touch ./30.m3u8
        sudo cat >./30.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=PB4gId2mPNc)
        EOL
      # 31NEW ZEALAND-8K 60看見紐西蘭
    - name: Get 31.m3u8
      run: |
        touch ./31.m3u8
        sudo cat >./31.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=yQqewUQy8DQ)
        EOL
        # 32LYING OVER DUBAI看見杜拜
    - name: Get 32.m3u8
      run: |
        touch ./32.m3u8
        sudo cat >./32.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=zMe6UvDCoY8)
        EOL
        # 33QT Relax Music的天堂海
    - name: Get 33.m3u8
      run: |
        touch ./33.m3u8
        sudo cat >./33.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=ROdgUPNjQ1A)
        EOL
        # 34FLYING OVER KOREA 看見韓國
    - name: Get 34.m3u8
      run: |
        touch ./34.m3u8
        sudo cat >./34.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=ff1vi9pPHR8)
        EOL
        # 35台灣空拍風景1
    - name: Get 35.m3u8
      run: |
        touch ./35.m3u8
        sudo cat >./35.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=iSgIBFBIeug&t=1300s)
        EOL
       # 36台灣空拍風景2
    - name: Get 36.m3u8
      run: |
        touch ./36.m3u8
        sudo cat >./36.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=yyQPJYw9unI)
        EOL
       # 37台灣空拍風景3
    - name: Get 37.m3u8
      run: |
        touch ./37.m3u8
        sudo cat >./37.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=-BjfCZUdYFw)
        EOL


    - name: git add
      run: |
        git add -A
        ls -la
    - name: commit & push
      run: |
        git commit -m "links are updated"
        git push
